import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { runHook } from '../../harness-source/scripts/hook-runner.mjs';
import { addedLines, scan } from '../../harness-source/hooks/core/push.mjs';
import { resolveDomain } from '../../harness-source/hooks/core/memory-guard.mjs';

const REPO = path.resolve(import.meta.dirname, '../..');
const ADAPTERS = path.join(REPO, 'harness-source/adapters');
const git = (cwd, args) => execFileSync('git', ['-c', 'user.email=t@example.invalid', '-c', 'user.name=t', ...args], { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();

// A synthetic repo with a bare "remote" so origin/<branch> exists; no network, no real push.
function repo() {
  const dir = fs.realpathSync.native(fs.mkdtempSync(path.join(os.tmpdir(), 'harness guards-')));
  git(dir, ['init', '-q', '-b', 'main']);
  fs.writeFileSync(path.join(dir, 'README.md'), '# x\n');
  git(dir, ['add', 'README.md']);
  git(dir, ['commit', '-q', '-m', 'init']);
  const remote = fs.mkdtempSync(path.join(os.tmpdir(), 'harness remote-'));
  git(remote, ['init', '-q', '--bare']);
  git(dir, ['remote', 'add', 'origin', remote]);
  git(dir, ['push', '-q', 'origin', 'main']);
  fs.mkdirSync(path.join(dir, '.claude'));
  return dir;
}
const env = (root, extra = {}) => ({ PATH: process.env.PATH, HOME: os.homedir(), CLAUDE_PROJECT_DIR: root, ...extra });
const bash = (command, cwd) => ({ hook_event_name: 'PreToolUse', session_id: 's', tool_name: 'Bash', tool_input: { command }, cwd });

test('commit guard: empty staged set blocks, staged files pass and are audited, -a/--amend pass, git -C and cd targets resolve, chained add&&commit is blocked by design', async () => {
  const root = repo();
  const run = (cmd, host = 'claude', cwd = root) => runHook({ host, hook: 'guard-commit', payload: bash(cmd, cwd), env: env(root), cwd, adaptersRoot: ADAPTERS });
  const empty = await run('git commit -m "x"');
  assert.equal(empty.exit, 2);
  assert.match(empty.stderr, /empty staged set/);
  const chained = await run('git add README.md && git commit -m "x"', 'codex');
  assert.equal(chained.exit, 2);
  assert.match(chained.stderr, /two separate calls/);
  fs.writeFileSync(path.join(root, 'a.txt'), 'a');
  git(root, ['add', 'a.txt']);
  const staged = await run('git commit -m "x"');
  assert.equal(staged.exit, 0);
  assert.match(fs.readFileSync(path.join(root, '.claude/audit.log'), 'utf8'), /COMMIT staged in .*: a\.txt/);
  assert.equal((await run('git commit -am "x"')).exit, 0);
  assert.equal((await run('git commit --amend --no-edit')).exit, 0);
  assert.equal((await run('ls')).exit, 0);
  const other = repo();
  const viaC = await run(`git -C "${other}" commit -m x`);
  assert.equal(viaC.exit, 2, 'the named repo (empty index) is inspected, not the caller cwd (staged)');
  assert.match(viaC.stderr, new RegExp(other.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  const viaCd = await run(`cd "${other}" && git commit -m x`, 'codex');
  assert.equal(viaCd.exit, 2);
  fs.writeFileSync(path.join(other, 'b.txt'), 'b');
  git(other, ['add', 'b.txt']);
  assert.equal((await run(`cd "${other}" && git commit -m x`)).exit, 0);
  const nogit = await runHook({ host: 'claude', hook: 'guard-commit', payload: bash('git commit -m x', root), env: env(root, { PATH: '/nonexistent' }), cwd: root, adaptersRoot: ADAPTERS });
  assert.equal(nogit.exit, 2, 'missing git is missing protection: block, never pass');
  assert.match(nogit.stderr, /git is not available/);
});

test('push guard: a secret added then removed still blocks (per-commit), paths only, credential files, allow markers, override audited, dry-run allowed', async () => {
  const root = repo();
  const run = (cmd, host = 'claude', extra = {}) => runHook({ host, hook: 'guard-push', payload: bash(cmd, root), env: env(root, extra), cwd: root, adaptersRoot: ADAPTERS });
  assert.equal((await run('git push origin main')).exit, 0, 'nothing unpushed');
  const token = `ghp_${'A'.repeat(36)}`;
  fs.writeFileSync(path.join(root, 'src.js'), `const t = "${token}";\n`);
  git(root, ['add', 'src.js']);
  git(root, ['commit', '-q', '-m', 'add token']);
  fs.writeFileSync(path.join(root, 'src.js'), 'const t = process.env.T;\n');
  git(root, ['add', 'src.js']);
  git(root, ['commit', '-q', '-m', 'remove token']);
  const blocked = await run('git push origin main', 'codex');
  assert.equal(blocked.exit, 2);
  assert.match(blocked.stderr, /Known-format secret\/token or private key in:\n    - src\.js/);
  assert.ok(!blocked.stderr.includes(token), 'the secret value is never echoed');
  assert.equal((await run('git push --dry-run origin main')).exit, 0);
  assert.equal((await run('git push origin :old-branch')).exit, 0);
  const override = await run('GUARD_PUSH_SKIP=1 git push origin main');
  assert.equal(override.exit, 0);
  assert.match(fs.readFileSync(path.join(root, '.claude/audit.log'), 'utf8'), /GUARD-PUSH OVERRIDE/);
  git(root, ['reset', '-q', '--hard', 'origin/main']);
  fs.writeFileSync(path.join(root, 'cfg.js'), 'const password = "correct-horse-battery"; // guard-push:allow\n');
  fs.writeFileSync(path.join(root, '.env.example'), 'KEY=\n');
  git(root, ['add', 'cfg.js', '.env.example']);
  git(root, ['commit', '-q', '-m', 'allowed']);
  assert.equal((await run('git push origin main')).exit, 0, 'allow marker and .example are respected');
  fs.writeFileSync(path.join(root, 'id_rsa'), 'not really a key');
  git(root, ['add', '-f', 'id_rsa']);
  git(root, ['commit', '-q', '-m', 'oops']);
  const file = await run('git push origin main');
  assert.equal(file.exit, 2);
  assert.match(file.stderr, /Credential file staged for push:\n    - id_rsa/);
  const nogit = await runHook({ host: 'claude', hook: 'guard-push', payload: bash('git push', root), env: env(root, { PATH: '/nonexistent' }), cwd: root, adaptersRoot: ADAPTERS });
  assert.equal(nogit.exit, 2);
  assert.match(nogit.stderr, /missing protection/);
  const lines = addedLines('+++ b/notes.md\n+AKIA' + 'B'.repeat(16) + '\n+++ b/app.py\n+x = 1\n+AKIA' + 'C'.repeat(16) + '\n');
  assert.deepEqual(lines.map((l) => l.file), ['app.py', 'app.py'], 'allowlisted .md is skipped — a documented limit');
  const hits = scan(lines, ['app.py', 'deploy/.env', 'deploy/.env.example']);
  assert.deepEqual(hits.high, ['app.py']);
  assert.deepEqual(hits.files, ['deploy/.env']);
});

test('memory guard: dormant without rules or below threshold, blocks once per domain per context, acknowledgement passes, skips docs/tests/config', async () => {
  const root = repo();
  const run = (payload, extra = {}) => runHook({ host: 'claude', hook: 'guard-memory', payload, env: env(root, extra), cwd: root, adaptersRoot: ADAPTERS });
  const edit = (file, session = 's1', agent = null) => ({ hook_event_name: 'PreToolUse', session_id: session, ...(agent ? { agent_id: agent } : {}), tool_name: 'Edit', tool_input: { file_path: path.join(root, file), new_string: 'x' } });
  fs.mkdirSync(path.join(root, '.agents/memory'), { recursive: true });
  fs.writeFileSync(path.join(root, '.agents/memory/errors.md'), 'e'.repeat(30_000));
  assert.equal((await run(edit('src/lib/ai/a.ts'))).state, 'dormant', 'no rules');
  fs.writeFileSync(path.join(root, '.claude/memory-domains.json'), JSON.stringify({ rules: [{ match: '^src/lib/([^/]+)/', domain: '$1' }], fallback: 'general', size_threshold_bytes: 24000 }));
  fs.writeFileSync(path.join(root, '.agents/memory/errors.md'), 'small');
  assert.equal((await run(edit('src/lib/ai/a.ts'))).state, 'dormant', 'below threshold');
  fs.writeFileSync(path.join(root, '.agents/memory/errors.md'), 'e'.repeat(30_000));
  const blocked = await run(edit('src/lib/ai/a.ts'));
  assert.equal(blocked.exit, 2);
  assert.match(blocked.stderr, /first code edit in domain "ai"/);
  assert.match(blocked.stderr, /--ack --domain ai/);
  assert.equal((await run(edit('src/app/page.tsx'))).exit, 0, 'fallback domain is soft');
  assert.equal((await run(edit('src/lib/ai/a.test.ts'))).exit, 0);
  assert.equal((await run(edit('.agents/memory/errors.md'))).exit, 0);
  assert.equal((await run(edit('src/lib/ai/config.json'))).exit, 0);
  const core = await import('../../harness-source/hooks/core/memory-guard.mjs');
  const ack = core.acknowledge({ projectRoot: root, host: 'claude', domain: 'ai', session: 's1' });
  assert.equal(ack.ok, true);
  assert.ok(ack.marker.includes(path.join('.agents/harness-state', 'memory-ack')));
  assert.equal((await run(edit('src/lib/ai/b.ts'))).exit, 0, 'acknowledged domain passes');
  assert.equal((await run(edit('src/lib/billing/b.ts'))).exit, 2, 'another domain blocks again');
  assert.equal((await run(edit('src/lib/ai/b.ts', 's2'))).exit, 2, 'another session is another context');
  assert.deepEqual(resolveDomain('src/lib/pay/x.ts', { rules: [{ match: '^src/lib/([^/]+)/', domain: '$1' }] }), { domain: 'pay', enforced: true });
  assert.equal(resolveDomain('other/x.ts', { rules: [{ match: '^src/', domain: 'src' }], fallback: 'general' }).enforced, false);
  assert.ok(!fs.existsSync('/tmp/claude-mem-s1'), 'no /tmp markers');
});
