import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { buildAll, renderAll } from '../../scripts/build-harness.mjs';
import { exportBundle, validateBundle } from '../../scripts/lib/bundle.mjs';
import { MARKER, diffPackage, readMarker, renderMarketplaces, renderWrappers, writePackage } from '../../scripts/lib/package-build.mjs';
import { WRAPPER_NOTE, wrapperCommandFor } from '../../harness-source/scripts/lib/wrapper.mjs';
import { verifyPackageRoot } from '../../harness-source/scripts/lib/locator.mjs';
import { parseFrontmatter } from '../../harness-source/scripts/lib/frontmatter.mjs';
import { addAssertion, addReceipt, newEvidence } from '../../harness-source/scripts/lib/evidence.mjs';

const FIXTURE = path.join(import.meta.dirname, 'fixtures/mini-repo');

function tmp() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'harness-pkg-'));
}

function copyFixture() {
  const dir = tmp();
  fs.cpSync(FIXTURE, dir, { recursive: true });
  return dir;
}

test('render is deterministic and the marker excludes itself', () => {
  const a = renderAll(FIXTURE);
  const b = renderAll(FIXTURE);
  for (const host of ['claude', 'codex']) {
    assert.deepEqual(a.rendered[host].marker, b.rendered[host].marker);
    assert.ok(!a.rendered[host].marker.files.some((f) => f.path === MARKER));
    assert.equal(a.rendered[host].marker.source_digest, a.sourceDigest);
  }
  assert.notEqual(a.rendered.claude.marker.payload_digest, a.rendered.codex.marker.payload_digest, 'per-host payloads differ');
});

test('skill rendering applies host frontmatter and codex metadata', () => {
  const { rendered } = renderAll(FIXTURE);
  const claudeSkill = rendered.claude.files.get('skills/demo/SKILL.md').toString();
  const { data } = parseFrontmatter(claudeSkill);
  assert.equal(data['disable-model-invocation'], true);
  assert.equal(data['argument-hint'], '[topic]');
  assert.ok(claudeSkill.includes('generated by scripts/build-harness.mjs'));
  const codexSkill = parseFrontmatter(rendered.codex.files.get('skills/demo/SKILL.md').toString()).data;
  assert.deepEqual(Object.keys(codexSkill), ['name', 'description']);
  const yaml = rendered.codex.files.get('skills/demo/agents/openai.yaml').toString();
  assert.match(yaml, /allow_implicit_invocation: false/);
  assert.match(yaml, /short_description: Demo skill for packaging tests\./);
  const manifest = JSON.parse(rendered.codex.files.get('.codex-plugin/plugin.json').toString());
  assert.deepEqual(Object.keys(manifest).sort(), ['description', 'name', 'skills', 'version']);
  const claudeManifest = JSON.parse(rendered.claude.files.get('.claude-plugin/plugin.json').toString());
  assert.equal(claudeManifest.name, 'harness');
  assert.equal(claudeManifest.skills, './skills/');
});

test('build writes identical bytes twice and passes the drift check; the installed-root check accepts it', () => {
  const out = tmp();
  buildAll(FIXTURE, out);
  const first = fs.readFileSync(path.join(out, 'packages/claude', MARKER), 'utf8');
  buildAll(FIXTURE, out);
  assert.equal(fs.readFileSync(path.join(out, 'packages/claude', MARKER), 'utf8'), first);
  const { rendered } = renderAll(FIXTURE);
  assert.deepEqual(diffPackage(path.join(out, 'packages/codex'), rendered.codex), []);
  for (const host of ['claude', 'codex']) {
    const check = verifyPackageRoot(path.join(out, 'packages', host), { host, expectedName: 'harness', expectedVersion: '0.0.1' });
    assert.deepEqual(check.errors, []);
  }
  assert.ok(fs.existsSync(path.join(out, '.claude-plugin/marketplace.json')));
  assert.ok(fs.existsSync(path.join(out, '.agents/plugins/marketplace.json')));
});

test('unexpected existing output is a conflict, not a deletion; stale owned files are removed', () => {
  const out = tmp();
  buildAll(FIXTURE, out);
  const pkgDir = path.join(out, 'packages/claude');
  fs.writeFileSync(path.join(pkgDir, 'stray.txt'), 'not ours');
  const { rendered } = renderAll(FIXTURE);
  assert.throws(() => writePackage(pkgDir, rendered.claude), /unexpected files/);
  assert.ok(fs.existsSync(path.join(pkgDir, 'stray.txt')), 'conflict must not delete');
  fs.rmSync(path.join(pkgDir, 'stray.txt'));
  const marker = readMarker(pkgDir);
  const stalePath = path.join(pkgDir, 'references/old.md');
  fs.writeFileSync(stalePath, 'old');
  marker.files.push({ path: 'references/old.md', sha256: '0'.repeat(64), bytes: 3 });
  fs.writeFileSync(path.join(pkgDir, MARKER), JSON.stringify(marker));
  writePackage(pkgDir, rendered.claude);
  assert.ok(!fs.existsSync(stalePath), 'previously generated file is pruned');
});

test('symlinks in the destination and in source are refused', () => {
  const out = tmp();
  buildAll(FIXTURE, out);
  const pkgDir = path.join(out, 'packages/claude');
  fs.symlinkSync(os.tmpdir(), path.join(pkgDir, 'escape'));
  const { rendered } = renderAll(FIXTURE);
  assert.throws(() => writePackage(pkgDir, rendered.claude), /symlink/);
  const repo = copyFixture();
  fs.symlinkSync(os.tmpdir(), path.join(repo, 'harness-source/references/link'));
  assert.throws(() => renderAll(repo), /symlinks are not allowed/);
});

test('missing referenced source fails the build', () => {
  const repo = copyFixture();
  fs.rmSync(path.join(repo, 'harness-source/references/demo.md'));
  assert.throws(() => renderAll(repo), /ENOENT|no such file/);
});

test('tampered marker or payload is detected by the installed-root check', () => {
  const out = tmp();
  buildAll(FIXTURE, out);
  const pkgDir = path.join(out, 'packages/codex');
  fs.appendFileSync(path.join(pkgDir, 'references/demo.md'), 'tamper');
  let check = verifyPackageRoot(pkgDir, { host: 'codex' });
  assert.ok(check.errors.some((e) => /content changed|byte length/.test(e)));
  buildAll(FIXTURE, out);
  const marker = readMarker(pkgDir);
  marker.version = '9.9.9';
  fs.writeFileSync(path.join(pkgDir, MARKER), JSON.stringify(marker));
  check = verifyPackageRoot(pkgDir, { host: 'codex', expectedVersion: '0.0.1' });
  assert.ok(check.errors.some((e) => /version/.test(e)));
  buildAll(FIXTURE, out);
  fs.writeFileSync(path.join(pkgDir, 'unexpected.md'), 'x');
  check = verifyPackageRoot(pkgDir, { host: 'codex' });
  assert.ok(check.errors.some((e) => /unknown extra/.test(e)));
  // Claude Code's own session lockfiles live in the installed root; they are host-owned, not tampering.
  const claudeRoot = path.join(out, 'packages/claude');
  fs.mkdirSync(path.join(claudeRoot, '.in_use'), { recursive: true });
  fs.writeFileSync(path.join(claudeRoot, '.in_use/12345'), '');
  const withLock = verifyPackageRoot(claudeRoot, { host: 'claude' });
  const codexLock = path.join(pkgDir, '.in_use'); fs.mkdirSync(codexLock, { recursive: true }); fs.writeFileSync(path.join(codexLock, '1'), '');
  assert.ok(verifyPackageRoot(pkgDir, { host: 'codex' }).errors.some((e) => /unknown extra/.test(e)), 'codex owns no such directory');
  assert.ok(!withLock.errors.some((e) => /unknown extra/.test(e)), `.in_use/ is host-owned on claude: ${withLock.errors.join('; ')}`);
});

test('packages leak no checkout paths, secrets or project data', () => {
  const { rendered } = renderAll(FIXTURE);
  for (const pkg of Object.values(rendered)) {
    for (const [p, bytes] of pkg.files) {
      const text = bytes.toString('utf8');
      assert.ok(!/\/Users\/|\/home\//.test(text), `${p} embeds a machine path`);
      assert.ok(!p.startsWith('.env') && !/\.env$/.test(p), `${p} looks like a secret file`);
      assert.ok(!/\.\.\/\.\.\/harness-source\//.test(text) || p.endsWith('SKILL.md') === false || text.includes('Never read'), `${p} depends on the checkout`);
    }
  }
});

test('export writes a bundle whose marketplaces resolve inside it and validate', () => {
  const repo = copyFixture();
  for (const rel of ['docs/harness/installation.md', 'docs/harness/capabilities.md', 'docs/harness/release-readiness.md']) {
    fs.mkdirSync(path.dirname(path.join(repo, rel)), { recursive: true });
    fs.writeFileSync(path.join(repo, rel), `# ${rel}\n`);
  }
  for (const rel of ['docs/harness/reviewer-capabilities.json', 'docs/harness/release-readiness.json']) {
    fs.writeFileSync(path.join(repo, rel), '{"fixture":true}\n');
  }
  const { harness, rendered } = renderAll(repo);
  const dest = path.join(tmp(), 'bundle');
  const stale = exportBundle({ repoRoot: repo, destDir: dest, harness, rendered, evidenceCurrent: false });
  assert.equal(stale.release.evidence_current, false);
  assert.ok(stale.release.evidence_missing.some((p) => /release-readiness\.json/.test(p)), 'evidence for other bytes is never shipped');
  assert.ok(!fs.existsSync(path.join(dest, 'docs/harness/release-readiness.json')));
  assert.deepEqual(validateBundle(dest), [], 'a bundle without live evidence validates on package integrity alone');
  assert.ok(validateBundle(path.join(tmp(), 'nope')).length > 0);
  // Shipped evidence must describe these bytes: fixture JSON that is not evidence is refused.
  const { release } = exportBundle({ repoRoot: repo, destDir: dest, harness, rendered, evidenceCurrent: true });
  assert.equal(release.version, '0.0.1');
  assert.ok(validateBundle(dest).some((e) => /release-readiness\.json/.test(e)), 'shipped evidence must be evidence for these digests');
  const good = (kind, inputs) => { const ev = newEvidence({ kind, mode: 'live', cli: {}, models: {}, effort: {}, configDigest: '0'.repeat(64), inputs }); const r = addReceipt(ev, path.join(repo, 'receipts'), `${kind}.json`, '{}'); addAssertion(ev, { name: 'x:ok', required: false, outcome: 'fail', observation: 'observed', receipt_sha256: r }); return ev; };
  fs.writeFileSync(path.join(repo, 'docs/harness/release-readiness.json'), JSON.stringify(good('release-readiness', { source_digest: rendered.claude.marker.source_digest, packages: { claude: { payload_digest: rendered.claude.marker.payload_digest }, codex: { payload_digest: rendered.codex.marker.payload_digest } } })));
  fs.writeFileSync(path.join(repo, 'docs/harness/reviewer-capabilities.json'), JSON.stringify(good('reviewer-capabilities', {})));
  exportBundle({ repoRoot: repo, destDir: dest, harness, rendered, evidenceCurrent: true });
  assert.deepEqual(validateBundle(dest), [], 'current evidence ships and validates whatever it observed — a failed row is a report, not a gate');
  const mp = JSON.parse(fs.readFileSync(path.join(dest, '.claude-plugin/marketplace.json'), 'utf8'));
  assert.equal(mp.plugins[0].source, './packages/claude');
  fs.appendFileSync(path.join(dest, 'packages/claude/references/demo.md'), 'x');
  assert.ok(validateBundle(dest).some((e) => /content changed|byte length/.test(e)));
  assert.throws(() => exportBundle({ repoRoot: repo, destDir: path.join(dest, 'packages'), harness, rendered, evidenceCurrent: true }), /refusing to export/);
});

test('marketplace manifests use relative ./ sources and the shared marketplace name', () => {
  const { harness } = renderAll(FIXTURE);
  const mps = renderMarketplaces(harness);
  const claude = JSON.parse(mps['.claude-plugin/marketplace.json']);
  const codex = JSON.parse(mps['.agents/plugins/marketplace.json']);
  assert.equal(claude.name, codex.name);
  assert.equal(claude.plugins[0].source, './packages/claude');
  assert.deepEqual(codex.plugins[0].source, { source: 'local', path: './packages/codex' });
});

test('wrappers: one per skill with a top-level legacy command, claude-only, written into the starter commands dir', () => {
  const REPO = path.resolve(import.meta.dirname, '../..');
  const { inventory, harness, rendered, wrappers } = renderAll(REPO);
  const expected = inventory.entries.map(wrapperCommandFor).filter(Boolean).sort();
  assert.deepEqual(expected, ['brainstorm', 'handoff', 'plan-feature', 'prime'], 'namespaced setup/start.md gets no wrapper');
  assert.deepEqual([...wrappers.keys()].sort(), expected);
  for (const [command, text] of wrappers) {
    const skill = inventory.entries.find((e) => wrapperCommandFor(e) === command).id;
    assert.ok(text.includes(WRAPPER_NOTE), `${command}: generated note`);
    assert.ok(text.includes(`Skill tool with skill \`harness:${skill}\` and args \`$ARGUMENTS\` verbatim`), `${command}: routes to the skill`);
    assert.ok(text.includes('mrozmk/AI_Coding_Starter@release'), `${command}: names the release channel`);
    assert.ok(rendered.claude.files.has(`templates/wrappers/${command}.md`), `${command}: packaged for claude`);
    assert.ok(!rendered.codex.files.has(`templates/wrappers/${command}.md`), `${command}: not packaged for codex`);
  }
  assert.deepEqual(renderWrappers({ repoRoot: REPO, inventory, harness }), wrappers);
  const out = tmp();
  buildAll(REPO, out);
  for (const command of expected) assert.equal(fs.readFileSync(path.join(out, '.claude/commands', `${command}.md`), 'utf8'), wrappers.get(command));
});
