// Renders one host package in memory from the inventory, then writes it with ownership rules:
// only inventory-listed paths are written, only previously-generated files are removed, any
// unexpected existing file is a conflict (never a recursive delete), symlink escapes refused.
import fs from 'node:fs';
import path from 'node:path';
import { fileEntries, recordsDigest } from '../../harness-source/scripts/lib/digest.mjs';
import { parseFrontmatter, serializeFrontmatter, serializeScalar } from '../../harness-source/scripts/lib/frontmatter.mjs';
import { assertInside, listFiles, readJson } from '../../harness-source/scripts/lib/fsx.mjs';
import { outputsFor, sourceDigestRecords } from './inventory.mjs';
import { CORES } from '../../harness-source/scripts/hook-runner.mjs';
import { renderWrapper, wrapperCommandFor, wrapperDescription } from '../../harness-source/scripts/lib/wrapper.mjs';

export const MARKER = 'harness-build.json';
export const GENERATED_NOTE = 'generated by scripts/build-harness.mjs from harness-source/ — edit the source, not this file';

const HOST_DIR = { claude: 'claude-code', codex: 'codex-cli' };

export function loadAdapterMeta(repoRoot, host) {
  return readJson(path.join(repoRoot, 'harness-source/adapters', HOST_DIR[host], 'adapter.json'));
}

// Wrapper commands for every skill with a top-level legacy command: Map command → file text.
// Claude-only (Codex has no project commands); the same texts land in the starter's .claude/commands/.
export function renderWrappers({ repoRoot, inventory, harness }) {
  const out = new Map();
  for (const entry of inventory.entries) {
    const command = wrapperCommandFor(entry);
    if (!command) continue;
    const { data } = parseFrontmatter(fs.readFileSync(path.join(repoRoot, entry.source), 'utf8'));
    out.set(command, renderWrapper({ command, skill: entry.id, description: data['wrapper-description'] ?? wrapperDescription(data.description), argumentHint: data['argument-hint'] ?? null, plugin: harness.name, marketplace: harness.marketplace_name, installSource: `${harness.marketplace_source}@${harness.release_ref}` }));
  }
  return out;
}

export function renderPackage({ repoRoot, inventory, harness, host, adapterMeta, sourceDigest, wrappers }) {
  const files = new Map();
  const put = (p, content) => {
    if (files.has(p)) throw new Error(`output path collision: ${p}`);
    files.set(p, Buffer.isBuffer(content) ? content : Buffer.from(content, 'utf8'));
  };
  const skills = {};
  const agents = {};
  for (const entry of inventory.entries) {
    const outs = outputsFor(entry, host);
    if (outs.length === 0) continue;
    if (entry.kind === 'manifest') {
      put(outs[0], `${JSON.stringify(renderManifest(harness, host, adapterMeta), null, 2)}\n`);
      continue;
    }
    const src = fs.readFileSync(path.join(repoRoot, entry.source));
    if (entry.kind === 'skill') {
      const rendered = renderSkill(src.toString('utf8'), entry, host, adapterMeta);
      put(outs[0], rendered.skill);
      if (rendered.openaiYaml) put(outs[1], rendered.openaiYaml);
      skills[entry.id] = outs[0];
    } else {
      put(outs[0], src);
      if (entry.kind === 'agent') agents[entry.id] = outs[0];
    }
  }
  if (host === 'claude') for (const [command, text] of wrappers) put(`templates/wrappers/${command}.md`, text);
  // Hook ids (as the native manifests name them) → packaged core path; validated below.
  const hooks = {};
  for (const [id, core] of Object.entries(CORES)) if (files.has(`hooks/core/${core}`)) hooks[id] = `hooks/core/${core}`;
  if (files.has('hooks/hooks.json')) hooks['hooks.json'] = 'hooks/hooks.json';
  const records = [...files].map(([p, bytes]) => ({ path: p, bytes }));
  const marker = {
    schema_version: 1,
    generated: GENERATED_NOTE,
    host,
    name: harness.name,
    version: harness.version,
    source_digest: sourceDigest ?? recordsDigest(sourceDigestRecords(inventory, repoRoot)),
    payload_digest: recordsDigest(records),
    skills,
    agents,
    hooks,
    files: fileEntries(records),
  };
  const problems = validateRendered({ files, marker, host });
  if (problems.length) throw new Error(`package ${host} invalid:\n  ${problems.join('\n  ')}`);
  return { files, marker };
}

// Package-level invariants checked before anything is written: every path is package-relative,
// every hook target exists, the native hooks manifest names only packaged runner/hook ids, and no
// project/private data rides along.
const PRIVATE_RE = /(^|\/)\.env(\.|$)|secret|credential|\.pem$|\.key$|(^|\/)user-profile\.md$|(^|\/)harness-state\//i;
export function validateRendered({ files, marker, host }) {
  const problems = [];
  for (const p of files.keys()) {
    if (path.posix.isAbsolute(p) || p.split('/').includes('..')) problems.push(`path not package-relative: ${p}`);
    if (PRIVATE_RE.test(p)) problems.push(`private-looking path packaged: ${p}`);
  }
  for (const [id, rel] of Object.entries(marker.hooks ?? {})) if (!files.has(rel)) problems.push(`hook target missing: ${id} -> ${rel}`);
  const manifest = files.get('hooks/hooks.json');
  if (manifest) {
    const parsed = JSON.parse(manifest.toString('utf8'));
    if (!files.has('scripts/hook-runner.mjs')) problems.push('hooks/hooks.json present but scripts/hook-runner.mjs not packaged');
    for (const groups of Object.values(parsed.hooks ?? {})) for (const g of groups) for (const h of g.hooks ?? []) {
      const m = h.command.match(/--host (\w+) --hook ([a-z-]+)/);
      if (!m) { problems.push(`hooks.json command not a runner invocation: ${h.command}`); continue; }
      if (m[1] !== host) problems.push(`hooks.json for ${host} names host ${m[1]}`);
      if (!marker.hooks?.[m[2]]) problems.push(`hooks.json names hook ${m[2]} with no packaged core`);
    }
  }
  for (const [p, bytes] of files) {
    if (!/\.(md|mjs|json|yaml)$/.test(p)) continue;
    const text = bytes.toString('utf8');
    if (/\/Users\/[a-z]|\/home\/[a-z]/.test(text)) problems.push(`machine path in ${p}`);
  }
  return problems;
}

function renderSkill(text, entry, host, adapterMeta) {
  const { data, body } = parseFrontmatter(text);
  if (!data.name || !data.description) throw new Error(`${entry.source}: SKILL.md needs name and description`);
  if (data.name !== entry.id) throw new Error(`${entry.source}: frontmatter name ${data.name} != inventory id ${entry.id}`);
  const fm = { name: data.name, description: data.description };
  for (const key of adapterMeta.skill_frontmatter_passthrough ?? []) {
    if (data[key] !== undefined) fm[key] = data[key];
  }
  Object.assign(fm, adapterMeta.skill_frontmatter ?? {});
  const skill = `${serializeFrontmatter(fm)}<!-- ${GENERATED_NOTE} -->\n\n${body}`;
  if (host !== 'codex') return { skill };
  const meta = adapterMeta.skill_metadata ?? {};
  const openaiYaml = [
    'interface:',
    `  display_name: ${serializeScalar(data['display-name'] ?? data.name)}`,
    `  short_description: ${serializeScalar(shortDescription(data.description))}`,
    'policy:',
    `  allow_implicit_invocation: ${meta.allow_implicit_invocation === true}`,
    '',
  ].join('\n');
  return { skill, openaiYaml };
}

function shortDescription(desc) {
  const first = desc.split(/(?<=\.)\s/)[0];
  return first.length > 120 ? `${first.slice(0, 117)}...` : first;
}

function renderManifest(harness, host, adapterMeta) {
  const base = {
    name: harness.name,
    version: harness.version,
    description: harness.description,
  };
  if (host === 'claude') {
    return {
      ...base,
      displayName: harness.display_name,
      author: harness.owner,
      license: harness.license,
      keywords: adapterMeta.manifest_keywords ?? [],
      skills: './skills/',
    };
  }
  return { ...base, skills: './skills/' };
}

export function readMarker(pkgDir) {
  const p = path.join(pkgDir, MARKER);
  return fs.existsSync(p) ? readJson(p) : null;
}

// Write a rendered package to disk under the ownership rules described at the top.
export function writePackage(pkgDir, { files, marker }) {
  const previous = readMarker(pkgDir);
  const owned = new Set([...(previous?.files ?? []).map((f) => f.path), MARKER]);
  const expected = new Set(files.keys());
  const { files: existing, symlinks } = listFiles(pkgDir);
  if (symlinks.length) throw new Error(`refusing to build into ${pkgDir}: symlinks present: ${symlinks.join(', ')}`);
  const conflicts = existing.filter((p) => !expected.has(p) && !owned.has(p));
  if (conflicts.length) {
    throw new Error(`refusing to build into ${pkgDir}: unexpected files not owned by a previous build:\n  ${conflicts.join('\n  ')}`);
  }
  fs.mkdirSync(pkgDir, { recursive: true });
  for (const p of existing) {
    if (owned.has(p) && !expected.has(p) && p !== MARKER) {
      const abs = path.join(pkgDir, p);
      assertInside(pkgDir, abs, 'stale output');
      fs.rmSync(abs);
    }
  }
  for (const [p, bytes] of files) {
    const abs = path.join(pkgDir, p);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    assertInside(pkgDir, path.dirname(abs), 'output directory');
    if (fs.existsSync(abs) && fs.lstatSync(abs).isSymbolicLink()) throw new Error(`output is a symlink: ${abs}`);
    fs.writeFileSync(abs, bytes);
  }
  fs.writeFileSync(path.join(pkgDir, MARKER), `${JSON.stringify(marker, null, 2)}\n`);
  pruneEmptyDirs(pkgDir);
}

function pruneEmptyDirs(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const abs = path.join(dir, entry.name);
    pruneEmptyDirs(abs);
    if (fs.readdirSync(abs).length === 0) fs.rmdirSync(abs);
  }
}

// Compare a rendered package with what is on disk; returns a list of drift descriptions.
export function diffPackage(pkgDir, { files, marker }) {
  const drift = [];
  const { files: existing } = listFiles(pkgDir);
  const expected = new Set([...files.keys(), MARKER]);
  for (const p of existing) if (!expected.has(p)) drift.push(`extra file: ${p}`);
  for (const [p, bytes] of files) {
    const abs = path.join(pkgDir, p);
    if (!fs.existsSync(abs)) drift.push(`missing file: ${p}`);
    else if (!fs.readFileSync(abs).equals(bytes)) drift.push(`content differs: ${p}`);
  }
  const onDisk = readMarker(pkgDir);
  if (!onDisk) drift.push(`missing ${MARKER}`);
  else if (JSON.stringify(onDisk) !== JSON.stringify(marker)) drift.push(`${MARKER} differs (source_digest/payload_digest/file list)`);
  return drift;
}

export function renderMarketplaces(harness) {
  const claude = {
    $schema: 'https://anthropic.com/claude-code/marketplace.schema.json',
    name: harness.marketplace_name,
    description: harness.description,
    owner: harness.owner,
    version: harness.version,
    plugins: [{
      name: harness.name,
      displayName: harness.display_name,
      description: harness.description,
      version: harness.version,
      source: './packages/claude',
      license: harness.license,
    }],
  };
  const codex = {
    name: harness.marketplace_name,
    interface: { displayName: harness.display_name },
    plugins: [{ name: harness.name, source: { source: 'local', path: './packages/codex' } }],
  };
  return {
    '.claude-plugin/marketplace.json': `${JSON.stringify(claude, null, 2)}\n`,
    '.agents/plugins/marketplace.json': `${JSON.stringify(codex, null, 2)}\n`,
  };
}
