// Project-side wrapper commands for plugin skills. A wrapper is a plain starter file (sync category A,
// never a `migrated` record): typing the bare command routes to the plugin skill without the
// /harness: prefix. Eligibility is the entry's explicit `wrapper` field — a command path, optionally
// one namespace segment deep. It replaced a legacy-path heuristic in 0.4.0: widening that regex to
// namespaced commands captured `setup-start`, whose legacy body must survive, and three `gates/*`
// paths classified `retired`, where a generated wrapper resurrects a tombstoned file in a downstream.
export const WRAPPER_NOTE = 'generated by scripts/build-harness.mjs from the skill inventory — edit the inventory or scripts/lib/wrapper.mjs, not this file';
export function wrapperCommandFor(entry) {
  return entry.kind === 'skill' && entry.wrapper ? entry.wrapper : null;
}

// `setup/create-PRD` is the command path; `/setup:create-PRD` is what a user types. Emitting the
// slash form as an invocation produces a command that silently does not resolve on Claude Code.
export function wrapperToken(command) {
  return command.replace(/\//g, ':');
}

// First sentence, hard-capped at MAX_WRAPPER_DESCRIPTION chars on a word boundary. A skill that wants
// a specific wrapper line sets `wrapper-description` in its frontmatter instead.
export const MAX_WRAPPER_DESCRIPTION = 80;
export function wrapperDescription(description) {
  const cut = description.search(/ — |\. |: /);
  let s = (cut > 0 ? description.slice(0, cut) : description).trim().replace(/\.$/, '');
  if (s.length > MAX_WRAPPER_DESCRIPTION) {
    const head = s.slice(0, MAX_WRAPPER_DESCRIPTION - 1);
    s = `${head.slice(0, Math.max(head.lastIndexOf(' '), 20)).replace(/[,;]$/, '')}…`;
  }
  return s;
}

// `installSource` (owner/repo@ref) adds the install hint; a downstream stub written next to a bound
// installation passes none — the plugin is already there.
export function renderWrapper({ command, skill, description, argumentHint = null, plugin = 'harness', marketplace = 'ai-coding-starter', installSource = null, boundRoot = null }) {
  const fm = [`description: ${description} (wrapper for the ${plugin} plugin skill)`];
  if (argumentHint) fm.push(`argument-hint: ${JSON.stringify(String(argumentHint))}`);
  const enable = installSource ? ` To enable it here: \`claude plugin install ${plugin}@${marketplace} --scope project\` (after \`claude plugin marketplace add ${installSource}\`), or start the session with \`claude --plugin-dir packages/claude\` for development.` : '';
  const where = boundRoot ? ` The plugin is bound at \`${boundRoot}\` (recorded in \`.agents/harness-version.json\` + \`.agents/harness-state/\`).` : '';
  const token = wrapperToken(command);
  return `---\n${fm.join('\n')}\n---\n<!-- ${WRAPPER_NOTE} -->\n\n# /${token} → ${plugin}:${skill}\n\nInvoke the Skill tool with skill \`${plugin}:${skill}\` and args \`$ARGUMENTS\` verbatim, then follow that skill — the same as the user typing \`/${plugin}:${skill}\`. Do nothing else first — no context loading, no work of your own.${where}\n\nIf the Skill tool reports the skill unknown, the \`${plugin}\` plugin is not enabled in this project. Say so and stop; do not fall back to an improvised version.${enable}\n`;
}
