// Project-side wrapper commands for plugin skills. A wrapper is a plain starter file (sync category A,
// never a `migrated` record): typing the bare command routes to the plugin skill without the
// /harness: prefix. Only a skill whose legacy command lived directly under .claude/commands/ gets one;
// namespaced legacy commands (setup/, maintain/, gates/) are invoked as /harness:<skill> by decision.
export const WRAPPER_NOTE = 'generated by scripts/build-harness.mjs from the skill inventory — edit the inventory or scripts/lib/wrapper.mjs, not this file';
export function wrapperCommandFor(entry) {
  if (entry.kind !== 'skill') return null;
  const hit = (entry.legacy ?? []).map(String).find((p) => /^\.claude\/commands\/[^/]+\.md$/.test(p));
  return hit ? hit.slice('.claude/commands/'.length, -'.md'.length) : null;
}

export function shortDescription(description) {
  const cut = description.search(/ — |\. |: /);
  return (cut > 0 ? description.slice(0, cut) : description).trim().replace(/\.$/, '');
}

// `installSource` (owner/repo@ref) adds the install hint; a downstream stub written next to a bound
// installation passes none — the plugin is already there.
export function renderWrapper({ command, skill, description, argumentHint = null, plugin = 'harness', marketplace = 'ai-coding-starter', installSource = null, boundRoot = null }) {
  const fm = [`description: ${shortDescription(description)} (wrapper for the ${plugin} plugin skill)`];
  if (argumentHint) fm.push(`argument-hint: ${JSON.stringify(String(argumentHint))}`);
  const enable = installSource ? ` To enable it here: \`claude plugin install ${plugin}@${marketplace} --scope project\` (after \`claude plugin marketplace add ${installSource}\`), or start the session with \`claude --plugin-dir packages/claude\` for development.` : '';
  const where = boundRoot ? ` The plugin is bound at \`${boundRoot}\` (recorded in \`.agents/harness-version.json\` + \`.agents/harness-state/\`).` : '';
  return `---\n${fm.join('\n')}\n---\n<!-- ${WRAPPER_NOTE} -->\n\n# /${command} → ${plugin}:${skill}\n\nInvoke the Skill tool with skill \`${plugin}:${skill}\` and args \`$ARGUMENTS\` verbatim, then follow that skill — the same as the user typing \`/${plugin}:${skill}\`. Do nothing else first — no context loading, no work of your own.${where}\n\nIf the Skill tool reports the skill unknown, the \`${plugin}\` plugin is not enabled in this project. Say so and stop; do not fall back to an improvised version.${enable}\n`;
}
