// Project-side wrapper commands for plugin skills. A wrapper is a plain starter file (sync category A,
// never a `migrated` record): typing the bare command routes to the plugin skill without the
// /harness: prefix. Eligibility is the entry's explicit `wrapper` field — a command path, optionally
// one namespace segment deep. It replaced a legacy-path heuristic in 0.4.0: widening that regex to
// namespaced commands captured `setup-start`, whose legacy body must survive, and three `gates/*`
// paths classified `retired`, where a generated wrapper resurrects a tombstoned file in a downstream.
export const WRAPPER_NOTE = 'generated by scripts/build-harness.mjs from the skill inventory — edit the inventory or scripts/lib/wrapper.mjs, not this file';
export function wrapperCommandFor(entry) {
  return entry.kind === 'skill' && entry.wrapper ? entry.wrapper : null;
}

// `setup/create-PRD` is the command path; `/setup:create-PRD` is what a user types. Emitting the
// slash form as an invocation produces a command that silently does not resolve on Claude Code.
export function wrapperToken(command) {
  return command.replace(/\//g, ':');
}

// First sentence, hard-capped at MAX_WRAPPER_DESCRIPTION chars on a word boundary. A skill that wants
// a specific wrapper line sets `wrapper-description` in its frontmatter instead.
export const MAX_WRAPPER_DESCRIPTION = 80;
export function wrapperDescription(description) {
  const cut = description.search(/ — |\. |: /);
  let s = (cut > 0 ? description.slice(0, cut) : description).trim().replace(/\.$/, '');
  if (s.length > MAX_WRAPPER_DESCRIPTION) {
    const head = s.slice(0, MAX_WRAPPER_DESCRIPTION - 1);
    s = `${head.slice(0, Math.max(head.lastIndexOf(' '), 20)).replace(/[,;]$/, '')}…`;
  }
  return s;
}

// `installSource` (owner/repo@ref) adds the install hint; a downstream stub written next to a bound
// installation passes none — the plugin is already there.
export function renderWrapper({ command, skill, description, argumentHint = null, plugin = 'harness', marketplace = 'ai-coding-starter', installSource = null, boundRoot = null }) {
  const fm = [`description: ${description} (wrapper for the ${plugin} plugin skill)`];
  if (argumentHint) fm.push(`argument-hint: ${JSON.stringify(String(argumentHint))}`);
  const enable = installSource ? ` To enable it here: \`claude plugin install ${plugin}@${marketplace} --scope project\` (after \`claude plugin marketplace add ${installSource}\`), or start the session with \`claude --plugin-dir packages/claude\` for development.` : '';
  const where = boundRoot ? ` The plugin is bound at \`${boundRoot}\` (recorded in \`.agents/harness-version.json\` + \`.agents/harness-state/\`).` : '';
  const token = wrapperToken(command);
  return `---\n${fm.join('\n')}\n---\n<!-- ${WRAPPER_NOTE} -->\n\n# /${token} → ${plugin}:${skill}\n\nInvoke the Skill tool with skill \`${plugin}:${skill}\` and args \`$ARGUMENTS\` verbatim, then follow that skill — the same as the user typing \`/${plugin}:${skill}\`. Do nothing else first — no context loading, no work of your own.${where}\n\nIf the Skill tool reports the skill unknown, the \`${plugin}\` plugin is not enabled in this project. Say so and stop; do not fall back to an improvised version.${enable}\n`;
}

// The command paths the generator can produce: one namespace segment deep, no colon — `wrapperToken`
// is what introduces the colon, so a colon in `command` means the caller derived it from a flat
// filename that merely *looks* like a nested wrapper's token (`setup:create-PRD.md`). Comparing
// tokens alone would map that file onto `setup/create-PRD` and delete a copy the project owns.
const WRAPPER_SEGMENT = '[A-Za-z0-9][A-Za-z0-9-]*';
const WRAPPER_COMMAND = new RegExp(`^${WRAPPER_SEGMENT}(?:/${WRAPPER_SEGMENT})?$`);

// The heading must name the file's *own* command path, and both the note and the heading must sit
// where `renderWrapper` puts them — frontmatter, note, blank line, heading. A free search would
// accept a hand-written command that quotes a retired wrapper inside a fenced example, and deleting
// that file (like deleting a wrapper copied or renamed elsewhere) would destroy project content.
export function isGeneratedWrapperFor(command, text, plugin = 'harness') {
  if (!WRAPPER_COMMAND.test(command)) return false;
  const lines = text.split('\n');
  if (lines[0] !== '---') return false;
  const close = lines.indexOf('---', 1);
  if (close < 1) return false;
  if (lines[close + 1] !== `<!-- ${WRAPPER_NOTE} -->` || lines[close + 2] !== '') return false;
  const prefix = `# /${wrapperToken(command)} → ${plugin}:`;
  const heading = lines[close + 3] ?? '';
  return heading.startsWith(prefix) && /^[a-z0-9][a-z0-9-]*$/.test(heading.slice(prefix.length));
}
